# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: market_place_api_development
  username: leamsi
  password: 123

test:
  <<: *default
  database: market_place_api_test
  username: leamsi
  password: 123

production:
  <<: *default
  database: market_place_api_production
  username: leamsi
  password: 123
